/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 bob.gltf --transform
Author: normajanethmr (https://sketchfab.com/normajanethmr)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/spongebob-draw-7e77932787364f4eb9ef722beeb37af8
Title: Spongebob Draw
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/bob-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.04, 0]} scale={0}>
        <mesh geometry={nodes.Object_6.geometry} material={materials.material_0} position={[-24.66, 66.46, 199.99]} scale={[205.88, 275.98, 124.71]} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.material_1} position={[-200.48, -142.42, 61.89]} scale={0.69} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.material_2} position={[-359.46, -275.14, -2.86]} rotation={[0, 0, 0.52]} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.material_3} position={[-202.26, 11.1, 202.07]} rotation={[0, 0, 0.41]} scale={[63.79, 29.96, 36.11]} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.material_1} position={[154.81, -142.43, 61.89]} scale={[-0.69, 0.69, 0.69]} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.material_2} position={[303.04, -275.12, 0.18]} rotation={[0, 0, -0.52]} scale={[-1, 1, 1]} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.material_4} position={[183.06, -7.81, 206.09]} rotation={[0, 0, 0.92]} scale={[57.36, 44.22, 34.92]} />
      </group>
    </group>
  )
}

useGLTF.preload('/bob-transformed.glb')
