/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 boxes.gltf --transform
Author: Pixel_Monster (https://sketchfab.com/ar.jethin)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cardboard-box-set-low-poly-5d3d508061e544739e37c685af235684
Title: Cardboard Box Set- Low Poly
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/boxes-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, -1.03, -58.86]} rotation={[Math.PI / 2, 0, 0]}>
        <group rotation={[-Math.PI, 0, 0]}>
          <mesh geometry={nodes.cardboard_box_set_lp__0.geometry} material={materials['Scene_-_Root']} position={[34.13, -29.43, 0]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/boxes-transformed.glb')
