/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 house.gltf --transform
Author: Home Design 3D (https://sketchfab.com/homedesign3d)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/yeni-proje-64-01813fb7408740b8abbc22a7848344aa
Title: Yeni proje ( 64 )
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/house-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['20191006-135226-gmt3']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['20200307-132146-gmt3']} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['20200307-132211-gmt3']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['20200307-13227-gmt3']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['20200316-215459-gmt3']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['20200321-211756-gmt3']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['20200321-235841-gmt3']} />
        <mesh geometry={nodes.Object_9.geometry} material={materials['20200321-235844-gmt3']} />
        <mesh geometry={nodes.Object_10.geometry} material={materials['20200326-224922-gmt3_ovcol737373colpic12contpic11']} />
        <mesh geometry={nodes.Object_11.geometry} material={materials['20200326-23116-gmt3']} />
        <mesh geometry={nodes.Object_12.geometry} material={materials['20200326-23119-gmt3']} />
        <mesh geometry={nodes.Object_13.geometry} material={materials['20200327-16955-gmt3_ovcole6e6e6colpic12contpic04']} />
        <mesh geometry={nodes.Object_14.geometry} material={materials['20200327-215338-gmt3']} />
        <mesh geometry={nodes.Object_15.geometry} material={materials['20200327-215359-gmt3']} />
        <mesh geometry={nodes.Object_16.geometry} material={materials['20200327-215420-gmt3']} />
        <mesh geometry={nodes.Object_17.geometry} material={materials['20200327-21546-gmt3']} />
        <mesh geometry={nodes.Object_18.geometry} material={materials['20200327-224354-gmt3_Wall_Entity_Material']} />
        <mesh geometry={nodes.Object_19.geometry} material={materials['20200329-22057-gmt3']} />
        <mesh geometry={nodes.Object_20.geometry} material={materials['20200329-22111-gmt3']} />
        <mesh geometry={nodes.Object_21.geometry} material={materials['20200329-22111-gmt3']} />
        <mesh geometry={nodes.Object_22.geometry} material={materials['20200329-2219-gmt3_Room_Entity_Material']} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.beige_006_Wall_Entity_Material} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.blanc_001_Room_Entity_Material} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.blanc_001_Room_Entity_Material} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.blanc_001_Room_Entity_Material} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.blanc_001_Room_Entity_Material} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.blanc_001_Room_Entity_Material} />
        <mesh geometry={nodes.Object_29.geometry} material={materials.blanc_001_Room_Entity_Material} />
        <mesh geometry={nodes.Object_30.geometry} material={materials.blanc_001_Room_Entity_Material} />
        <mesh geometry={nodes.Object_31.geometry} material={materials.blanc_001_Room_Entity_Material} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.blanc_001_Room_Entity_Material} />
        <mesh geometry={nodes.Object_33.geometry} material={materials.blanc_001_Room_Entity_Material} />
        <mesh geometry={nodes.Object_34.geometry} material={materials.blanc_001_Room_Entity_Material} />
        <mesh geometry={nodes.Object_35.geometry} material={materials.blanc_001_Room_Entity_Material} />
        <mesh geometry={nodes.Object_36.geometry} material={materials.etagere_006___livreblanc} />
        <mesh geometry={nodes.Object_37.geometry} material={materials.blanc_001_Room_Entity_Material} />
        <mesh geometry={nodes.Object_38.geometry} material={materials.blanc_001_Room_Entity_Material} />
        <mesh geometry={nodes.Object_39.geometry} material={materials.etagere_006___livreblanc} />
        <mesh geometry={nodes.Object_40.geometry} material={materials.blanc_001_Room_Entity_Material} />
        <mesh geometry={nodes.Object_41.geometry} material={materials.etagere_006___terrecuite} />
        <mesh geometry={nodes.Object_42.geometry} material={materials.blanc_001_Room_Entity_Material} />
        <mesh geometry={nodes.Object_43.geometry} material={materials.blanc_001_Room_Entity_Material} />
        <mesh geometry={nodes.Object_44.geometry} material={materials.blanc_001_Room_Entity_Material} />
        <mesh geometry={nodes.Object_45.geometry} material={materials.blanc_001_Room_Entity_Material} />
        <mesh geometry={nodes.Object_46.geometry} material={materials.blanc_001_Room_Entity_Material} />
        <mesh geometry={nodes.Object_47.geometry} material={materials.fake_mat_119_58_93_255} />
        <mesh geometry={nodes.Object_48.geometry} material={materials.fake_mat_141_136_134_255} />
        <mesh geometry={nodes.Object_49.geometry} material={materials.fake_mat_141_136_134_255} />
        <mesh geometry={nodes.Object_50.geometry} material={materials.fake_mat_156_30_37_255} />
        <mesh geometry={nodes.Object_51.geometry} material={materials.fake_mat_183_153_43_255} />
        <mesh geometry={nodes.Object_52.geometry} material={materials.fake_mat_189_190_193_255} />
        <mesh geometry={nodes.Object_53.geometry} material={materials.fake_mat_189_190_193_255} />
        <mesh geometry={nodes.Object_54.geometry} material={materials.fake_mat_198_171_155_255} />
        <mesh geometry={nodes.Object_55.geometry} material={materials.fake_mat_198_171_155_255} />
        <mesh geometry={nodes.Object_56.geometry} material={materials.fake_mat_225_112_28_255} />
        <mesh geometry={nodes.Object_57.geometry} material={materials.fake_mat_233_222_192_255} />
        <mesh geometry={nodes.Object_58.geometry} material={materials.fake_mat_235_232_226_255} />
        <mesh geometry={nodes.Object_59.geometry} material={materials.fake_mat_235_232_226_255} />
        <mesh geometry={nodes.Object_60.geometry} material={materials.fake_mat_252_252_252_255} />
        <mesh geometry={nodes.Object_61.geometry} material={materials.fake_mat_255_255_255_32} />
        <mesh geometry={nodes.Object_62.geometry} material={materials.fake_mat_34_36_39_255} />
        <mesh geometry={nodes.Object_63.geometry} material={materials.fake_mat_34_36_39_255} />
        <mesh geometry={nodes.Object_64.geometry} material={materials.fake_mat_41_70_127_255} />
        <mesh geometry={nodes.Object_65.geometry} material={materials.fake_mat_65_102_48_255} />
        <mesh geometry={nodes.Object_66.geometry} material={materials.fake_mat_65_102_48_255} />
        <mesh geometry={nodes.Object_67.geometry} material={materials.fake_mat_73_60_48_255} />
        <mesh geometry={nodes.Object_68.geometry} material={materials.fake_mat_73_60_48_255} />
        <mesh geometry={nodes.Object_69.geometry} material={materials.fake_mat_7_6_6_255} />
        <mesh geometry={nodes.Object_70.geometry} material={materials.fake_mat_7_6_6_255} />
        <mesh geometry={nodes.Object_71.geometry} material={materials.gris_006_Room_Entity_Material} />
        <mesh geometry={nodes.Object_72.geometry} material={materials.gris_006_Room_Entity_Material} />
        <mesh geometry={nodes.Object_73.geometry} material={materials.blanc_001_Room_Entity_Material} />
        <mesh geometry={nodes.Object_74.geometry} material={materials.blanc_001_Room_Entity_Material} />
        <mesh geometry={nodes.Object_75.geometry} material={materials.blanc_001_Room_Entity_Material} />
        <mesh geometry={nodes.Object_76.geometry} material={materials.kitchen_classic_style_base_cabinet_oven_003___phong4sg} />
        <mesh geometry={nodes.Object_77.geometry} material={materials.blanc_001_Room_Entity_Material} />
        <mesh geometry={nodes.Object_78.geometry} material={materials.blanc_001_Room_Entity_Material} />
        <mesh geometry={nodes.Object_79.geometry} material={materials.blanc_001_Room_Entity_Material} />
        <mesh geometry={nodes.Object_80.geometry} material={materials.blanc_001_Room_Entity_Material} />
        <mesh geometry={nodes.Object_81.geometry} material={materials.blanc_001_Room_Entity_Material} />
        <mesh geometry={nodes.Object_82.geometry} material={materials.mur_vegetal_off___phong151} />
        <mesh geometry={nodes.Object_83.geometry} material={materials.mur_vegetal_off___phong151} />
        <mesh geometry={nodes.Object_84.geometry} material={materials.blanc_001_Room_Entity_Material} />
        <mesh geometry={nodes.Object_85.geometry} material={materials.blanc_001_Room_Entity_Material} />
        <mesh geometry={nodes.Object_86.geometry} material={materials.blanc_001_Room_Entity_Material} />
        <mesh geometry={nodes.Object_87.geometry} material={materials.blanc_001_Room_Entity_Material} />
        <mesh geometry={nodes.Object_88.geometry} material={materials.mur_vegetal_off___phong151} />
        <mesh geometry={nodes.Object_89.geometry} material={materials.mur_vegetal_off___phong151} />
        <mesh geometry={nodes.Object_90.geometry} material={materials.mur_vegetal_off___phong151} />
        <mesh geometry={nodes.Object_91.geometry} material={materials.mur_vegetal_off___phong151} />
        <mesh geometry={nodes.Object_92.geometry} material={materials.blanc_001_Room_Entity_Material} />
        <mesh geometry={nodes.Object_93.geometry} material={materials.scan_buffet_003_blanc___bois_001} />
        <mesh geometry={nodes.Object_94.geometry} material={materials.scan_buffet_003_blanc___bois_001} />
        <mesh geometry={nodes.Object_95.geometry} material={materials.scan_buffet_003_blanc___bois_grisc} />
        <mesh geometry={nodes.Object_96.geometry} material={materials.blanc_001_Room_Entity_Material} />
        <mesh geometry={nodes.Object_97.geometry} material={materials.blanc_001_Room_Entity_Material} />
        <mesh geometry={nodes.Object_98.geometry} material={materials.blanc_001_Room_Entity_Material} />
        <mesh geometry={nodes.Object_99.geometry} material={materials.blanc_001_Room_Entity_Material} />
        <mesh geometry={nodes.Object_100.geometry} material={materials.blanc_001_Room_Entity_Material} />
        <mesh geometry={nodes.Object_101.geometry} material={materials.blanc_001_Room_Entity_Material} />
        <mesh geometry={nodes.Object_102.geometry} material={materials.blanc_001_Room_Entity_Material} />
        <mesh geometry={nodes.Object_103.geometry} material={materials.blanc_001_Room_Entity_Material} />
        <mesh geometry={nodes.Object_104.geometry} material={materials.blanc_001_Room_Entity_Material} />
        <mesh geometry={nodes.Object_105.geometry} material={materials.blanc_001_Room_Entity_Material} />
        <mesh geometry={nodes.Object_106.geometry} material={materials.blanc_001_Room_Entity_Material} />
        <mesh geometry={nodes.Object_107.geometry} material={materials.blanc_001_Room_Entity_Material} />
        <mesh geometry={nodes.Object_108.geometry} material={materials.blanc_001_Room_Entity_Material} />
        <mesh geometry={nodes.Object_109.geometry} material={materials.vitrine_004_bis___mat_urnesg} />
      </group>
    </group>
  )
}

useGLTF.preload('/house-transformed.glb')
