/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 scope.gltf --transform
Author: Touati_Fellouh (https://sketchfab.com/Touati_Fellouh)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stereo-microscope-9d9b102e11334a42bbe8e7901285e111
Title: Stereo Microscope
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/scope-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.45}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0.96, -0.9]} scale={0.14}>
            <mesh geometry={nodes.Object_4.geometry} material={materials['2-METAL1']} />
            <mesh geometry={nodes.Object_5.geometry} material={materials['3-METAL2']} />
          </group>
          <group position={[-0.26, 1.69, -0.44]} rotation={[0.95, 0, -Math.PI / 2]} scale={0.07}>
            <mesh geometry={nodes.Object_9.geometry} material={materials['4-BLACK_PARTS']} />
            <mesh geometry={nodes.Object_10.geometry} material={materials['4-BLACK_PARTS']} />
            <mesh geometry={nodes.Object_11.geometry} material={materials['4-BLACK_PARTS']} />
            <mesh geometry={nodes.Object_12.geometry} material={materials['Material.015']} />
            <mesh geometry={nodes.Object_13.geometry} material={materials['5-BLACK_PARTS2']} />
          </group>
          <mesh geometry={nodes.Object_7.geometry} material={materials['8-LAMP']} position={[0, 1.32, -0.16]} rotation={[-0.64, 0, 0]} scale={[0.14, 0.1, 0.14]} />
          <mesh geometry={nodes.Object_15.geometry} material={materials['1-BASE']} position={[-0.29, 2.98, 0.96]} rotation={[0.99, 0, 0]} scale={0.16} />
          <mesh geometry={nodes.Object_17.geometry} material={materials['1-BASE']} position={[0, 1.59, -1.03]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={0.04} />
          <mesh geometry={nodes.Object_19.geometry} material={materials['6-LENS_1']} position={[-0.28, 3.27, 1.41]} rotation={[0.99, 0, 0]} scale={0.17} />
          <mesh geometry={nodes.Object_21.geometry} material={materials['7-LENS_2']} position={[-0.28, 3.27, 1.41]} rotation={[0.99, 0, 0]} scale={0.17} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scope-transformed.glb')
